parameters:
#  thrift.client.class: Overblog\ThriftBundle\Client\ThriftClient
#  thrift.client.test.class: Overblog\ThriftBundle\Client\ThriftTestClient
  thrift.warmer.class: SmartGecko\ThriftBundle\CacheWarmer\ThriftCacheWarmer
  thrift.factory: SmartGecko\ThriftBundle\Factory\ThriftFactory

services:
  thrift.warmer:
    class: %thrift.warmer.class%
    arguments: [@service_container]
    tags:
      - { name: "kernel.cache_warmer", priority: "10" }

  thrift.factory:
    class: %thrift.factory%
    arguments: [%thrift.config.services%]